services:
  db:
    image: postgres:15
    container_name: odoo17-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      TZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"        # expose PostgreSQL ra host
    volumes:
      - odoo17-db-data:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:17.0
    container_name: odoo17
    depends_on:
      - db
    ports:
      - "8069:8069"   # web
      - "8072:8072"   # longpolling/live chat
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo17-web-data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf:ro
      - ./addons:/mnt/extra-addons
      - ./logs:/var/log/odoo
    restart: unless-stopped

volumes:
  odoo17-db-data:
  odoo17-web-data:
